import random

class Flashcard:
    def __init__(self, question, answer):
        self.question = question
        self.answer = answer

class FlashcardQuiz:
    def __init__(self):
        self.flashcards = []

    def add_flashcard(self, flashcard):
        self.flashcards.append(flashcard)

    def quiz(self):
        random.shuffle(self.flashcards)
        for flashcard in self.flashcards:
            input("Press Enter to see the question...")
            print(flashcard.question)
            input("Press Enter to see the answer...")
            print(flashcard.answer)

def main():
    quiz = FlashcardQuiz()

    quiz.add_flashcard(Flashcard("What is the capital of France?", "Paris"))
    quiz.add_flashcard(Flashcard("What is the capital of Spain?", "Madrid"))
    quiz.add_flashcard(Flashcard("What is the capital of Italy?", "Rome"))
    quiz.add_flashcard(Flashcard("What is the capital of Germany?", "Berlin"))
    quiz.add_flashcard(Flashcard("What is the capital of the United Kingdom?", "London"))
    quiz.add_flashcard(Flashcard("What is the capital of the United States?", "Washington D.C."))
    quiz.add_flashcard(Flashcard("What is the capital of Canada?", "Ottawa"))
    quiz.add_flashcard(Flashcard("What is the capital of Australia?", "Canberra"))
    quiz.add_flashcard(Flashcard("What is the capital of Japan?", "Tokyo"))
    quiz.add_flashcard(Flashcard("What is the capital of China?", "Beijing"))
    quiz.add_flashcard(Flashcard("What is the capital of India?", "New Delhi"))
    quiz.add_flashcard(Flashcard("What is the capital of Brazil?", "Brasília"))
    quiz.add_flashcard(Flashcard("What is the capital of Russia?", "Moscow"))
    quiz.add_flashcard(Flashcard("What is the capital of South Africa?", "Pretoria"))
    quiz.add_flashcard(Flashcard("What is the capital of Egypt?", "Cairo"))
    quiz.add_flashcard(Flashcard("What is the capital of Nigeria?", "Abuja"))
    quiz.add_flashcard(Flashcard("What is the capital of Kenya?", "Nairobi"))
    quiz.add_flashcard(Flashcard("What is the capital of Mexico?", "Mexico City"))
    quiz.add_flashcard(Flashcard("What is the capital of Argentina?", "Buenos Aires"))
    quiz.add_flashcard(Flashcard("What is the capital of Chile?", "Santiago"))
    quiz.add_flashcard(Flashcard("What is the capital of Peru?", "Lima"))
    quiz.add_flashcard(Flashcard("What is the capital of Colombia?", "Bogotá"))
    quiz.add_flashcard(Flashcard("What is the capital of Venezuela?", "Caracas"))
    quiz.add_flashcard(Flashcard("What is the capital of Cuba?", "Havana"))
    quiz.add_flashcard(Flashcard("What is the capital of Jamaica?", "Kingston"))
    quiz.add_flashcard(Flashcard("What is the capital of Haiti?", "Port-au-Prince"))
    quiz.add_flashcard(Flashcard("What is the capital of the Dominican Republic?", "Santo Domingo"))
    quiz.add_flashcard(Flashcard("What is the capital of Puerto Rico?", "San Juan"))
    quiz.add_flashcard(Flashcard("What is the capital of Costa Rica?", "San José"))
    quiz.add_flashcard(Flashcard("What is the capital of Panama?", "Panama City"))
    quiz.add_flashcard(Flashcard("What is the capital of Ecuador?", "Quito"))
    quiz.add_flashcard(Flashcard("What is the capital of Peru?", "Lima"))
    quiz.add_flashcard(Flashcard("What is the capital of Bolivia?", "La Paz"))
    quiz.add_flashcard(Flashcard("What is the capital of Paraguay?", "Asunción"))
    quiz.add_flashcard(Flashcard("What is the capital of Uruguay?", "Montevideo"))
    quiz.add_flashcard(Flashcard("What is the capital of Australia?", "Canberra"))
    quiz.add_flashcard(Flashcard("What is the capital of New Zealand?", "Wellington"))
    quiz.add_flashcard(Flashcard("What is the capital of Indonesia?", "Jakarta"))
    quiz.add_flashcard(Flashcard("What is the capital of South Korea?", "Seoul"))
    quiz.add_flashcard(Flashcard("What is the capital of North Korea?", "Pyongyang"))
    quiz.add_flashcard(Flashcard("What is the capital of Thailand?", "Bangkok"))
    quiz.add_flashcard(Flashcard("What is the capital of Vietnam?", "Hanoi"))
    quiz.add_flashcard(Flashcard("What is the capital of Malaysia?", "Kuala Lumpur"))
    quiz.add_flashcard(Flashcard("What is the capital of Singapore?", "Singapore"))
    quiz.add_flashcard(Flashcard("What is the capital of Taiwan?", "Taipei"))
    quiz.add_flashcard(Flashcard("What is the capital of Turkey?", "Ankara"))
    quiz.add_flashcard(Flashcard("What is the capital of Iran?", "Tehran"))
    quiz.add_flashcard(Flashcard("What is the capital of Iraq?", "Baghdad"))
    quiz.add_flashcard(Flashcard("What is the capital of Saudi Arabia?", "Riyadh"))
    quiz.add_flashcard(Flashcard("What is the capital of Greece?", "Athens"))
    quiz.add_flashcard(Flashcard("What is the capital of Germany?", "Berlin"))
    quiz.add_flashcard(Flashcard("What is the capital of Monaco?", "Monaco"))
    quiz.add_flashcard(Flashcard("What is the capital of Romania?", "Bucharest"))
    quiz.add_flashcard(Flashcard("What is the capital of Bulgaria?", "Sofia"))
    quiz.add_flashcard(Flashcard("What is the capital of Hungary?", "Budapest"))
    quiz.add_flashcard(Flashcard("What is the capital of Poland?", "Warsaw"))
    quiz.add_flashcard(Flashcard("What is the capital of Ukraine?", "Kyiv"))
    quiz.add_flashcard(Flashcard("What is the capital of Belarus?", "Minsk"))
    quiz.add_flashcard(Flashcard("What is the capital of Lithuania?", "Vilnius"))
    quiz.add_flashcard(Flashcard("What is the capital of Latvia?", "Riga"))
    quiz.add_flashcard(Flashcard("What is the capital of Estonia?", "Tallinn"))
    quiz.add_flashcard(Flashcard("What is the capital of Finland?", "Helsinki"))
    quiz.add_flashcard(Flashcard("What is the capital of Sweden?", "Stockholm"))
    quiz.add_flashcard(Flashcard("What is the capital of Norway?", "Oslo"))
    quiz.add_flashcard(Flashcard("What is the capital of Denmark?", "Copenhagen"))
    quiz.add_flashcard(Flashcard("What is the capital of Ireland?", "Dublin"))
    quiz.add_flashcard(Flashcard("What is the capital of Portugal?", "Lisbon"))
    quiz.add_flashcard(Flashcard("What is the capital of Switzerland?", "Bern"))
    quiz.add_flashcard(Flashcard("What is the capital of the Netherlands?", "Amsterdam"))
    quiz.add_flashcard(Flashcard("What is the capital of Belgium?", "Brussels"))
    quiz.add_flashcard(Flashcard("What is the capital of Luxembourg?", "Luxembourg City"))
    quiz.add_flashcard(Flashcard("What is the capital of Austria?", "Vienna"))
    quiz.add_flashcard(Flashcard("What is the capital of Czech Republic?", "Prague"))
    quiz.add_flashcard(Flashcard("What is the capital of Slovakia?", "Bratislava"))
    quiz.add_flashcard(Flashcard("What is the capital of Croatia?", "Zagreb"))
    quiz.add_flashcard(Flashcard("What is the capital of Slovenia?", "Ljubljana"))
    quiz.add_flashcard(Flashcard("What is the capital of Bosnia and Herzegovina?", "Sarajevo"))
    quiz.add_flashcard(Flashcard("What is the capital of Serbia?", "Belgrade"))
    quiz.add_flashcard(Flashcard("What is the capital of Montenegro?", "Podgorica"))
    quiz.add_flashcard(Flashcard("What is the capital of Albania?", "Tirana"))
    quiz.add_flashcard(Flashcard("What is the capital of Macedonia?", "Skopje"))
    quiz.add_flashcard(Flashcard("What is the capital of Kosovo?", "Pristina"))
    quiz.add_flashcard(Flashcard("What is the capital of Liechtenstein?", "Vaduz"))
    quiz.add_flashcard(Flashcard("What is the capital of San Marino?", "San Marino"))
    quiz.add_flashcard(Flashcard("What is the capital of Vatican City?", "Vatican City"))
    quiz.add_flashcard(Flashcard("What is the capital of Morocco?", "Rabat"))
    quiz.add_flashcard(Flashcard("What is the capital of Algeria?", "Algiers"))
    quiz.add_flashcard(Flashcard("What is the capital of Tunisia?", "Tunis"))
    quiz.add_flashcard(Flashcard("What is the capital of Libya?", "Tripoli"))
    quiz.add_flashcard(Flashcard("What is the capital of Egypt?", "Cairo"))
    quiz.add_flashcard(Flashcard("What is the capital of Sudan?", "Khartoum"))
    quiz.add_flashcard(Flashcard("What is the capital of South Sudan?", "Juba"))
    quiz.add_flashcard(Flashcard("What is the capital of Eritrea?", "Asmara"))
    quiz.add_flashcard(Flashcard("What is the capital of Djibouti?", "Djibouti"))
    quiz.add_flashcard(Flashcard("What is the capital of Somalia?", "Mogadishu"))
    quiz.add_flashcard(Flashcard("What is the capital of Kenya?", "Nairobi"))
    quiz.add_flashcard(Flashcard("What is the capital of Uganda?", "Kampala"))
    quiz.add_flashcard(Flashcard("What is the capital of Rwanda?", "Kigali"))
    quiz.add_flashcard(Flashcard("What is the capital of Burundi?", "Bujumbura"))
    quiz.add_flashcard(Flashcard("What is the capital of Tanzania?", "Dodoma"))
    quiz.add_flashcard(Flashcard("What is the capital of Zambia?", "Lusaka"))
    quiz.add_flashcard(Flashcard("What is the capital of Zimbabwe?", "Harare"))
    quiz.add_flashcard(Flashcard("What is the capital of Mozambique?", "Maputo"))
    quiz.add_flashcard(Flashcard("What is the capital of Madagascar?", "Antananarivo"))
    quiz.add_flashcard(Flashcard("What is the capital of Malawi?", "Lilongwe"))
    quiz.add_flashcard(Flashcard("What is the capital of Angola?", "Luanda"))
    quiz.add_flashcard(Flashcard("What is the capital of Namibia?", "Windhoek"))
    quiz.add_flashcard(Flashcard("What is the capital of Botswana?", "Gaborone"))
    quiz.add_flashcard(Flashcard("What is the capital of Lesotho?", "Maseru"))
    quiz.add_flashcard(Flashcard("What is the capital of Swaziland?", "Mbabane"))
    quiz.add_flashcard(Flashcard("What is the capital of Mauritius?", "Port Louis"))
    quiz.add_flashcard(Flashcard("What is the capital of Comoros?", "Moroni"))
    quiz.add_flashcard(Flashcard("What is the capital of Seychelles?", "Victoria"))
    quiz.add_flashcard(Flashcard("What is the capital of Ethiopia?", "Addis Ababa"))
    quiz.add_flashcard(Flashcard("What is the capital of Afghanistan?", "Kabul"))
    quiz.add_flashcard(Flashcard("What is the capital of Pakistan?", "Islamabad"))
    quiz.add_flashcard(Flashcard("What is the capital of Nepal?", "Kathmandu"))
    quiz.add_flashcard(Flashcard("What is the capital of Bhutan?", "Thimphu"))
    quiz.add_flashcard(Flashcard("What is the capital of Bangladesh?", "Dhaka"))
    quiz.add_flashcard(Flashcard("What is the capital of Sri Lanka?", "Colombo"))
    quiz.add_flashcard(Flashcard("What is the capital of Maldives?", "Malé"))
    quiz.add_flashcard(Flashcard("What is the capital of Myanmar?", "Naypyidaw"))
    quiz.add_flashcard(Flashcard("What is the capital of Laos?", "Vientiane"))
    quiz.add_flashcard(Flashcard("What is the capital of Cambodia?", "Phnom Penh"))


    print("Welcome to the Capitals Flashcard Quiz App!")
    input("Press Enter to start the quiz...")

    quiz.quiz()

    print("Thanks for playing!")

if __name__ == "__main__":
    main()
